# Generated by Django 2.2.6 on 2019-11-01 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChestionarAdjustments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('form_name', models.CharField(default='', max_length=100)),
                ('date', models.DateTimeField()),
                ('q1', models.CharField(default='', max_length=100)),
                ('q2', models.CharField(default='', max_length=100)),
                ('q3', models.CharField(default='', max_length=100)),
                ('q4', models.CharField(default='', max_length=100)),
                ('q5', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ChestionarMentalHealth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('form_name', models.CharField(default='', max_length=100)),
                ('date', models.DateTimeField()),
                ('q1', models.CharField(default='', max_length=100)),
                ('q2', models.CharField(default='', max_length=100)),
                ('q3', models.CharField(default='', max_length=100)),
                ('q4', models.CharField(default='', max_length=100)),
                ('q5', models.CharField(default='', max_length=100)),
                ('q6', models.CharField(default='', max_length=100)),
                ('q7', models.CharField(default='', max_length=100)),
                ('q8', models.CharField(default='', max_length=100)),
                ('q9', models.CharField(default='', max_length=100)),
                ('q10', models.CharField(default='', max_length=100)),
                ('q11', models.CharField(default='', max_length=100)),
                ('q12', models.CharField(default='', max_length=100)),
                ('q13', models.CharField(default='', max_length=100)),
                ('q14', models.CharField(default='', max_length=100)),
                ('q15', models.CharField(default='', max_length=100)),
                ('q16', models.CharField(default='', max_length=100)),
                ('q17', models.CharField(default='', max_length=100)),
                ('q18', models.CharField(default='', max_length=100)),
                ('q19', models.CharField(default='', max_length=100)),
                ('q20', models.CharField(default='', max_length=100)),
                ('q21', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ChestionarOrganizationalCulture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('form_name', models.CharField(default='', max_length=100)),
                ('date', models.DateTimeField()),
                ('q1', models.CharField(default='', max_length=100)),
                ('q2', models.CharField(default='', max_length=100)),
                ('q3', models.CharField(default='', max_length=100)),
                ('q4', models.CharField(default='', max_length=100)),
                ('q5', models.CharField(default='', max_length=100)),
                ('q6', models.CharField(default='', max_length=100)),
                ('q7', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ChestionarSelfConfidence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('form_name', models.CharField(default='', max_length=100)),
                ('date', models.DateTimeField()),
                ('q1', models.CharField(default='', max_length=100)),
                ('q2', models.CharField(default='', max_length=100)),
                ('q3', models.CharField(default='', max_length=100)),
                ('q4', models.CharField(default='', max_length=100)),
                ('q5', models.CharField(default='', max_length=100)),
                ('q6', models.CharField(default='', max_length=100)),
                ('q7', models.CharField(default='', max_length=100)),
                ('q8', models.CharField(default='', max_length=100)),
                ('q9', models.CharField(default='', max_length=100)),
                ('q10', models.CharField(default='', max_length=100)),
                ('q11', models.CharField(default='', max_length=100)),
                ('q12', models.CharField(default='', max_length=100)),
                ('q13', models.CharField(default='', max_length=100)),
                ('q14', models.CharField(default='', max_length=100)),
                ('q15', models.CharField(default='', max_length=100)),
                ('q16', models.CharField(default='', max_length=100)),
                ('q17', models.CharField(default='', max_length=100)),
                ('q18', models.CharField(default='', max_length=100)),
                ('q19', models.CharField(default='', max_length=100)),
                ('q20', models.CharField(default='', max_length=100)),
                ('q21', models.CharField(default='', max_length=100)),
                ('q22', models.CharField(default='', max_length=100)),
                ('q23', models.CharField(default='', max_length=100)),
                ('q24', models.CharField(default='', max_length=100)),
                ('q25', models.CharField(default='', max_length=100)),
                ('q26', models.CharField(default='', max_length=100)),
                ('q27', models.CharField(default='', max_length=100)),
                ('q28', models.CharField(default='', max_length=100)),
                ('q29', models.CharField(default='', max_length=100)),
                ('q30', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('user_name', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
